name: Build and Push Kong Image

on:
  push:
    paths:
      - kong-gateway/Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        platform:
          - linux/arm64
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set image tag (Commit ID or Tag name)
        id: tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Kong Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/kong-gateway:${{ env.IMAGE_TAG }} \
            --file kong-gateway/Dockerfile kong-gateway

      - name: Push Kong Image
        run: |
          docker push ghcr.io/${{ github.repository }}/kong-gateway:${{ env.IMAGE_TAG }}

      - name: Save image tag
        run: echo "${{ env.IMAGE_TAG }}" > image_tag.txt

      - name: Upload image tag
        uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt
