name: Build and Push Kong Image

on:
  push:
    paths:
      - kong-gateway/Dockerfile
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Kongイメージのタグ"
        required: false

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        platform:
          - linux/arm64
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set image tag (Commit ID or Input tag name)
        id: tag
        run: |
          if [ ! -z "${{ github.event.inputs.image_tag }}" ]; then
            echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Build Kong Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/kong-gateway:${{ env.IMAGE_TAG }} \
            --file kong-gateway/Dockerfile kong-gateway

      - name: Push Kong Image
        run: |
          docker push ghcr.io/${{ github.repository }}/kong-gateway:${{ env.IMAGE_TAG }}

      - name: Scan image using Trivy
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}/kong-gateway:${{ env.IMAGE_TAG }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          output: "trivy-scan-results.txt"

      - name: Upload scan results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-scan-results.txt

      - name: Tag as latest and push
        if: ${{ success() && steps.trivy.conclusion == 'success' }}
        run: |
          docker tag ghcr.io/${{ github.repository }}/kong-gateway:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository }}/kong-gateway:latest
          docker push ghcr.io/${{ github.repository }}/kong-gateway:latest
