name: Build and Push APIOps Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build APIOPS Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/konnect-apiops -f apiops/Dockerfile apiops/

      - name: Push APIOPS Image
        run: |
          docker push ghcr.io/${{ github.repository }}/konnect-apiops
